### ISSUE TITLE
How to run Dask benchmark

### ISSUE THREAD

**Issue by mrocklin** [StanfordLegion/task-bench#40]
Please excuse my ignorance here, I'm not familiar with CFFI. A small amount of web searching didn't yield much.  I started going through the README, but the instructions there seemed to be about building everything, which I was hoping to avoid if possible.  

If you have any tips, they would be welcome.  Not a big deal if not.

```
(dev) MROCKLIN-MLT:dask mrocklin$ python task_bench_direct.py
Traceback (most recent call last):
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/cparser.py", line 294, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/pycparser/c_parser.py", line 1848, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:5:18: before: char

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "task_bench_direct.py", line 209, in <module>
    execute_task_bench()
  File "task_bench_direct.py", line 189, in execute_task_bench
    from task_bench_core import ffi, c
  File "/Users/mrocklin/workspace/task-bench/dask/task_bench_core.py", line 36, in <module>
    ffi.cdef(core_header)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/cparser.py", line 347, in parse
    self._internal_parse(csource)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/cparser.py", line 352, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/cparser.py", line 296, in _parse
    self.convert_pycparser_error(e, csource)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/cffi/cparser.py", line 325, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "typedef __signed char int8_t;"
<cdef source string>:5:18: before: char
```

**Comment by elliottslaughter** [comment]
Er, that should work. What OS version are you on? A very similar command works for me on Ubuntu 16.04:

```
$ LD_LIBRARY_PATH=$PWD/core python dask/task_bench.py 
Running Task Benchmark
...
Total Tasks 16
Total Dependencies 0
Total FLOPs 0
Total Bytes 0
Elapsed Time 7.095185e-02 seconds
FLOP/s 0.000000e+00
B/s 0.000000e+00
```

It's probably happening because CFFI only parses a subset of C, but we currently rely on parsing real C header files. (I don't like duplicating my headers just to make them parseable.) We've had issues with this in the past, at the moment we've just been working around them on a case-by-case basis. Maybe there's a more principled way to do it (but again, I don't like code duplication...).

**Comment by mrocklin** [comment]
This was on an OSX machine, but I'll try this again on my Ubuntu machine
tomorrow.

**Comment by mrocklin** [comment]
```
mrocklin@carbon:~/workspace/task-bench$ python dask/task_bench_direct.py 
Traceback (most recent call last):
  File "dask/task_bench_direct.py", line 209, in <module>
    execute_task_bench()
  File "dask/task_bench_direct.py", line 189, in execute_task_bench
    from task_bench_core import ffi, c
  File "/home/mrocklin/workspace/task-bench/dask/task_bench_core.py", line 37, in <module>
    c = ffi.dlopen("libcore.so")
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/cffi/api.py", line 795, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/cffi/api.py", line 790, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library libcore.so: libcore.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcore.so'
```

Is the right thing to build all?

```
DEFAULT_FEATURES=0 USE_LEGION=1 ./get_deps.sh
./build_all.sh
```

Or is there a slimmer set of things should build?

**Comment by elliottslaughter** [comment]
You should be able to just do `make -C core`.

The commands you qouted are what you'd use for a full build but you can skip them if you don't need any other systems.

**Comment by mrocklin** [comment]
Not quite there yet (also, thank you for helping me deal with my ignorance here)

```
mrocklin@carbon:~/workspace/task-bench$ git clean -xfd
Removing core/core.o
Removing core/core_c.o
Removing core/core_kernel.o
Removing core/core_random.o
Removing core/libcore.a
Removing core/libcore.so
Removing core/libcore_s.a
Removing core/siphash.o
Removing core/timer.o
Removing dask/__pycache__/

mrocklin@carbon:~/workspace/task-bench$ make -C core
make: Entering directory '/home/mrocklin/workspace/task-bench/core'
g++  -std=c++11 -fPIC -O3 -mavx2 -mfma -c -o core.o core.cc
g++  -std=c++11 -fPIC -O3 -mavx2 -mfma -c -o core_c.o core_c.cc
g++  -std=c++11 -fPIC -O3 -mavx2 -mfma -c -o core_kernel.o core_kernel.cc
g++  -std=c++11 -fPIC -O3 -mavx2 -mfma -c -o timer.o timer.cc
cc  -std=c11 -fPIC -O3 -mavx2 -mfma -c -o core_random.o core_random.c
cc  -std=c11 -fPIC -O3 -mavx2 -mfma -c -o siphash.o siphash.c
rm -f libcore.a
ar rc libcore.a core.o core_c.o core_kernel.o timer.o core_random.o siphash.o
rm -f libcore.so
g++  -shared -L. -Wl,--whole-archive -lcore -Wl,--no-whole-archive -o libcore.so.0
mv libcore.so.0 libcore.so
ln -sf libcore.a libcore_s.a
make: Leaving directory '/home/mrocklin/workspace/task-bench/core'

mrocklin@carbon:~/workspace/task-bench$ python dask/task_bench_direct.py 
Traceback (most recent call last):
  File "dask/task_bench_direct.py", line 209, in <module>
    execute_task_bench()
  File "dask/task_bench_direct.py", line 189, in execute_task_bench
    from task_bench_core import ffi, c
  File "/home/mrocklin/workspace/task-bench/dask/task_bench_core.py", line 37, in <module>
    c = ffi.dlopen("libcore.so")
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/cffi/api.py", line 795, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/cffi/api.py", line 790, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library libcore.so: libcore.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcore.so'
```

**Comment by elliottslaughter** [comment]
Can you try something like:

```
LD_LIBRARY_PATH=$PWD/core python dask/task_bench.py
```

Or on macOS:

```
DYLD_LIBRARY_PATH=$PWD/core python dask/task_bench.py
```

I think it's just not finding the shared object right now.

**Comment by mrocklin** [comment]
Yes, that seems to work

Looking at the README it seems like I can control things with keywords like the following

    LD_LIBRARY_PATH=$PWD/core python dask/task_bench_direct.py -steps 4 -width 4000 -type trivial

I think that this is enough for me to take a look, run things through cProfile and the dashboard, and take a quick look at what current bottlenecks are.

Thanks @elliottslaughter !  Closing.

**Comment by elliottslaughter** [comment]
Yes, that's right. A typical configuration would be to use `-width N` where `N` is the number of cores on your machine, and a higher value for steps like `-steps 1000` (note that `task_bench.py` still suffers the `O(N^2)` cost issue, so use `task_bench_direct.py` if you want to test high numbers of steps). And then you can fiddle with `-type` to get different dependency patterns.

You can run `-h` for a summary of all the options.
